### ISSUE TITLE
TypeError: ClientSession.__init__() got an unexpected keyword argument 'params'

### ISSUE THREAD

**Issue by mxft** [layerqa/aiocryptopay#2]
В ClientSession() библиотеки aiohttp передается `**kwargs`, который содержит ключи `params` и `headers`, но так как в последней версии aiohttp ClientSession не принимает в себя params, код выбрасывает ошибку.

Вот неработающая функция:
```
    def get_session(self, **kwargs):
        """Get cached session. One session per instance."""
        if isinstance(self._session, ClientSession) and not self._session.closed:
            return self._session

        ssl_context = ssl.create_default_context(cafile=certifi.where())
        connector = TCPConnector(ssl=ssl_context)

        self._session = ClientSession(connector=connector, **kwargs)
        return self._session
```

**Comment by layerqa** [comment]
Fixed [remove **kwargs from _make_request func](https://github.com/layerqa/aiocryptopay/commit/cb1812680ef457a1dd70a2f25545c9107f4115be)
