### ISSUE TITLE
Пример из README работает, но завершается с ошибкой.

### ISSUE THREAD

**Issue by fkpancho** [layerqa/aiocryptopay#7]
![error](https://github.com/layerqa/aiocryptopay/assets/100464709/313bc23b-1fa7-46c4-8583-5f631301afd5)

Что я делаю не так?

В таком варианте завершается без ошибок.

```
async def main():
    crypto = AioCryptoPay(token=token, network=Networks.TEST_NET)
    profile = await crypto.get_me()

    print(profile)
    session = crypto.get_session()
    await session.close()
    time.sleep(0.05)
```

**Comment by layerqa** [comment]
Да, забыли добавить функцию закрытия сессии aiohttp в примерах. Если хочешь, то можешь сделать pull request с доработкой README.

**Comment by layerqa** [comment]
> Да, забыли добавить функцию закрытия сессии aiohttp в примерах. Если хочешь, то можешь сделать pull request с доработкой README.

И да, ты можешь обойтись без crypto.get_session(), а сразу закрывать сессию crypto.close(), как это сделано в примере вебхуков.

**Comment by fkpancho** [comment]
> 
Как бы обойтись без магических чисел после закрытия сессии? В примере выше - time.sleep(0.05)
