### ISSUE TITLE
Dependency Conflict with pydantic in aiocryptopay Version 0.2.8

### ISSUE THREAD

**Issue by Latand** [layerqa/aiocryptopay#8]
I encountered a dependency conflict issue related to the `aiocryptopay` package version 0.2.8 and its requirement for `pydantic<2.0.0 and >=1.10.7`. This specific requirement is incompatible with several other libraries that depend on different versions of `pydantic`, making it difficult to use `aiocryptopay` in conjunction with other packages.

As an example, the library `aiogram` (versions `3.0.0rc2`, `3.0.0b9`) depends on `pydantic<3 and >=2.1.1`, which conflicts with the constraints set by `aiocryptopay`.

The error message I received:
```
ERROR: Cannot install -r .\requirements.txt (line 1) and -r .\requirements.txt (line 25) because these package versions have conflicting dependencies.

The conflict is caused by:
aiocryptopay 0.2.8 depends on pydantic<2.0.0 and >=1.10.7
aiogram 3.0.0rc2 depends on pydantic<3 and >=2.1.1
aiocryptopay 0.2.8 depends on pydantic<2.0.0 and >=1.10.7
aiocryptopay 0.2.8 depends on pydantic<2.0.0 and >=1.10.7
aiogram 3.0.0b9 depends on pydantic~=2.1.1
```

Environment details:
- Python version: Python 3.10
- OS: Windows

The issue prevents me from using `aiocryptopay` in projects that also depend on other libraries with conflicting `pydantic` requirements. I kindly request an update to support a broader range of `pydantic` versions.

Thank you

**Comment by layerqa** [comment]
Hello, sorry for the long wait for an answer, I don't quite understand how to fix this conflict, can you explain how to fix this conflict or make a pull request with an update

**Comment by layerqa** [comment]
Fixed https://github.com/layerqa/aiocryptopay/commit/3154dc9d4a0d0a518b8852b63948cc3d18180e29
