### ISSUE TITLE
Перестал работать функция get_amount_by_fiat

### ISSUE THREAD

**Issue by kerosenone** [layerqa/aiocryptopay#9]
Вчера работала.

    summa = db[call.from_user.id]["invest"]

    print(summa)

    # Get amount in crypto by fiat summ
    amount = await crypto.get_amount_by_fiat(summ=float(summa), asset='USDT', target='USD')
    invoice = await crypto.create_invoice(asset='USDT', amount=float(amount))
    
    
![image](https://github.com/layerqa/aiocryptopay/assets/92634014/9ed0bf01-e53f-412d-99f3-f2bc4b38c3eb)

**Comment by layerqa** [comment]
update package
